### PR TITLE
#74 make a proper demo 

### PR DESCRIPTION
**Pull request by m-w-w**
Early iteration of the demo. Would appreciate feedback!

### CODE REVIEW

**Comment by FrancoisPgm** [comment]
Maybe printing the confounds shape along with their values would make it easier to see the difference between the flexible strategy and the pre-defined one. 
Also I believe Pierre had the idea of plotting a second correlation matrix computed without regressing the confounds, to stress their importance.

**Comment by pbellec** [comment]
@all-contributors add @m-w-w for doc

**Comment by pbellec** [comment]
@all-contributors add @FrancoisPgm for review

**Comment by pbellec** [comment]
LGTM.

**Pull request merged**
