### PR TITLE
Refactor compcor

### PR DESCRIPTION
**Pull request by htwangtw**
Not sure if this will increase the complexity or reduce it.

 - compcor option and anatomical mask all resolved in `_find_compcor`
 - Use a dictionary to catch invalid input
 - Catch invalid input for compcor and acompcor_combined, and invalid combinations of the two

Feel free to reject/merge to see if this fits your plan.

### CODE REVIEW

**Comment by pbellec** [comment]
Great job! I think you managed to simplify the implementation of compcor to something almost digestible - I still find it really convoluted, but hey that's just the algorithm, not the code. Really appreciate you adding sensible error messages. I think there's a bug in the revised code though, I've added a comment. Should be super easy to fix.

**Comment by htwangtw** [comment]
> I think there's a bug in the revised code though, I've added a comment. Should be super easy to fix.
I couldn't find the said comment. Can you check again it's submitted?

**Review by pbellec — CHANGES_REQUESTED** [review]

**Comment by pbellec** [comment]
> > I think there's a bug in the revised code though, I've added a comment. Should be super easy to fix.
> 
> I couldn't find the said comment. Can you check again it's submitted?

You are right, I had not finalized the submission of the review :(

**Comment by pbellec** [comment]
OK so I see this PR is on a branch, so I am going to merge and request for you to review the merged branch including the bug fix.

**Pull request merged**
