### PR TITLE
NF Validate input files and limit input to image files

### LINKED ISSUE #129: require nifti file as input and validate extension.
This makes the API a bit less flexible, but it would enable to validate that users are using the correct file for their strategy. This is important for the ICA based denoising strategies.

### LINKED ISSUE #139: Allow cifti and gifti as input file
fMRIprep has good support for surface-based file now. Worth adding support for these file types.

### PR DESCRIPTION
**Pull request by htwangtw**
Closes #129 and closes #139.

**This PR will limit input files to processed image files.** 
Associated confound tsv will be automatically detected. 

* check input file type (nifti, cifti, and gifti generated by fMRIprep)
* modified tests accordingly; add new test data for file name check
* ensure ICA-AROMA related methods have the correct files, leading to some implementation change
    * add parameter `Confounds.ica_aroma` accepting options: `full`, `basic`, `None` (default)
    * strategy `ica_aroma` and  parameter `ica_aroma=None` are mutually exclusive
    * `ica_aroma="full"` checks if `desc-smoothAROMAnonaggr_bold` exist.
    * `ica_aroma="basic"` uses default nifti output and aroma columns in confound file.
    * remove aroma related confounds from `missing_desc-confounds_regressors.tsv` to test valid image file but missing correct regressors
* flag error when confound files pre and post fmriprep v20.2.0 (`_desc-confounds_timeseries.tsv` and`_desc-confounds_regressors.tsv`) are both present (Let me know if this one is overkill)

### CODE REVIEW

**Comment by pbellec** [comment]
Very exciting to see this! 

I'm going to review the code asap.

Also, I have tweaked code mountain to disable the warnings on duplicated code (docs really). I don't think it's ideal to have this doc duplicated though. Maybe when there is a permanent home (and doc) for load_confounds we can link to a central doc repo. But for now with the current design it's hard to avoid.

**Review by pbellec — APPROVED** [review]

**Comment by pbellec** [comment]
Huge thanks for this PR, @htwangtw those checks are essential given the complexity of the denoising variants. This is likely going to help many users who try to use an ICA denoising strategy and avoid many mistakes. I've reviewed quite carefully and everything look good to me. I've only left minor comments. As soon as those are addressed, I'll merge the PR.

**Comment by htwangtw** [comment]
Thank you @pbellec! I have implemented the suggested changes!

**Comment by pbellec** [comment]
Huge thanks again @htwangtw for your contribution!

**Pull request merged**
