### PR TITLE
[MNT] Add warning message in README.md

### LINKED ISSUE #150: Add a warning about migration to nilearn
Now the existing functionality of this package is fully part of nilearn. Any future maintenance will be on nilearn. We should update the read me file and perhaps warning   in the code.

### PR DESCRIPTION
**Pull request by htwangtw**
Merge this PR when Nilearn make a release.

Closes #150.

### CODE REVIEW

**Comment by pbellec** [comment]
LGTM. There is just a minor typo "to on nilearn" -> "to nilearn". Otherwise ready to merge.

**Comment by htwangtw** [comment]
Not sure nilearn will be released next yet. Once the release happens, this will be a one click job!

Thanks for looking out for these details!

**Comment by pbellec** [comment]
@htwangtw now that nilearn 0.9 is out, should we merge this?

**Comment by htwangtw** [comment]
Sure! I shall update the links

**Comment by pbellec** [comment]
LGTM! Thanks.

**Pull request merged**
